import TodoListComponent from "@/components/todoListComponent";

export const metadata = {
    title: 'Todo list page',
    description: 'Generated by create next app',
};


export default function TodoListPage() {
    return(
        <div>
            <h1 className="is-size-1 my-5 has-text-weight-bold has-text-centered">Todo list page</h1>

            <TodoListComponent />
        </div>
    );
}